# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belttest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='user_trip',
            new_name='user_wish',
        ),
    ]
