# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belttest', '0002_auto_20161029_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='added_by',
        ),
    ]
