# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belttest', '0003_remove_wish_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
